name: Atualizador Lotofácil

on:
  schedule:
    # Horários ajustados para o sorteio das 21h (Brasil)
    # O servidor usa UTC (+3h em relação ao Brasil)
    
    # 1ª Tentativa: 21:15 BRT (00:15 UTC do dia seguinte)
    - cron: '15 0 * * *'
    
    # 2ª Tentativa: 21:45 BRT (00:45 UTC) - Caso atrase
    - cron: '35 0 * * *'
    
    # 3ª Tentativa: 21:45 BRT (00:45 UTC) - Caso atrase
    - cron: '45 0 * * *'
    
    # 4ª Tentativa: 22:30 BRT (01:30 UTC) - Garantia final
    - cron: '30 1 * * *'
    - cron: '45 12 * * *'
  workflow_dispatch: # Permite rodar manualmente no botão

jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write # IMPORTANTE: Permite salvar os arquivos

    steps:
      - name: Baixar repositório
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar bibliotecas
        run: pip install -r requirements.txt

      - name: Rodar script
        env:
          # AQUI: Injeta a chave da IA que você salvou nos Secrets
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }} 
        run: python update_loto.py

      - name: Salvar mudanças (Commit)
        run: |
          git config --global user.name 'LotoBot'
          git config --global user.email 'bot@noreply.github.com'
          git add api/*.json
          # Só commita se houver mudança nos arquivos
          git diff --quiet && git diff --staged --quiet || (git commit -m "Dados atualizados automagicamente" && git push)
