name: Atualizador Lotofacil

on:
  schedule:
    - cron: '25 0 * * *'
    - cron: '35 0 * * *'
    - cron: '30 1 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write

    steps:
      - name: Baixar repositório
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' 

      - name: Instalar bibliotecas
        run: |
          pip install requests
          pip install groq

      - name: Rodar script
        env:
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
        run: python update_loto.py

      - name: Salvar mudanças
        run: |
          git config --global user.name 'LotoBot'
          git config --global user.email 'bot@noreply.github.com'
          git add api/*.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "Dados atualizados via Groq" && git push)
